@startuml

rectangle "node-stratum-server" as node_stratum_server {
    object Worker
    Worker : name : string

    object mining.submit

    mining.submit : name : string
    mining.submit : jobId : string
    mining.submit : extraNonce2 : string
    mining.submit : nTime : string
    mining.submit : nonce : string

    object ShareDTO
    ShareDTO :  workerName : string
    ShareDTO :  jobId : string
    ShareDTO :  difficulty : string
    ShareDTO :  extraNonce1 : string
    ShareDTO :  extraNonce2 : strings
    ShareDTO :  nTime : string
    ShareDTO :  nonce : string
    ShareDTO :  remoteAddress : string
    ShareDTO :  localPort : string

    object ConnectionInfo
    ConnectionInfo : worker : string
    ConnectionInfo : remoteAddress : string
    ConnectionInfo : localPort : string

}


rectangle "node-open-mining-portal" as node_open_mining_portal {
    object User
    User : workerName (payment address): string

}




/'
note bottom of layer_connection_manager {
    Handle connections, messages
    Prevent flooding, spamming
    Convert mining.submit in ShareDTO
    Passes ShareDTO in StratumController
}'/


@enduml
/'

 {
                name        : message.params[0],
                jobId       : message.params[1],
                extraNonce2 : message.params[2],
                nTime       : message.params[3],
                nonce       : message.params[4]
            },

   var result = _this.jobManager.processShare(
                    params.jobId,
                    client.previousDifficulty,
                    client.difficulty,
                    client.extraNonce1,
                    params.extraNonce2,
                    params.nTime,
                    params.nonce,
                    client.remoteAddress,
                    client.socket.localPort,
                    params.name,logger
                );

'/